### ISSUE TITLE
Bypassing world border easily

### ISSUE THREAD

**Issue by root-mega** [MrMarL/Oneblock#16]
Latest version of the plugin
1.20.1
Papermc latest version as of 08/08/2023
https://youtu.be/t8Xz2wPCmWw

**Comment by MrMarL** [comment]
Try to enable /ob autojoin

**Comment by root-mega** [comment]
> Try to enable /ob autojoin

okay just letting you know that that bug exists

**Comment by MrMarL** [comment]
Fixed
