### ISSUE TITLE
Block respawn rate too slow

### ISSUE THREAD

**Issue by TheodoreMeyer** [MrMarL/OneBlock#23]
I chose to use this plugin for my spigot server and ran into a problem:

Block spawn rate is too slow and not fixable without in game commands.
Sometimes I'm waiting up to a second for the block to respawn.

In Creative it is a larger issue, as you can break any block quickly.  In survival it depends on the block and when in the tick time you break it. I fell out of the void world after breaking it twice on level one.

Fixes: There are two fixes possible fixes for this. You can either have the plugin place a obsidian or bedrock block under the one-block, A lot of plugins do this just in case. Or change the code so that it checks if the spot where the one-block is air and places a block back more often. TPS should be around 20 for this though.

Also: if you add the block beneath, is there a way to make the block water or Lava.

**Comment by MrMarL** [comment]
If you are a member of the island, the block appears instantly.
