### ISSUE TITLE
LOG4J

### ISSUE THREAD

**Issue by Wuemeli** [MrMarL/Oneblock#8]
07.01 08:56:23 [Server] INFO Stopping main thread (Ignore any thread death message you see! - DO NOT REPORT THREAD DEATH TO PAPER)
07.01 08:56:23 [Server] INFO 2022-01-07 08:56:23,899 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.io.LoggerPrintStream caught java.lang.ThreadDeath logging ReusableSimpleMessage: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.save(java.io.File)" because "Oneblock.Oneblock.data" is null java.lang.ThreadDeath
07.01 08:56:23 [Server] INFO at java.base/java.lang.Thread.stop(Thread.java:942)
07.01 08:56:23 [Server] INFO at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:1029)
07.01 08:56:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:839)
07.01 08:56:23 [Server] INFO at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1001)
07.01 08:56:23 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:29)
07.01 08:56:23 [Server] WARN at oneblock.jar//Oneblock.Oneblock.saveData(Oneblock.java:931)
07.01 08:56:23 [Server] WARN at oneblock.jar//Oneblock.Oneblock.onDisable(Oneblock.java:319)
07.01 08:56:23 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
07.01 08:56:23 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401)
07.01 08:56:23 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537)
07.01 08:56:23 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376)
07.01 08:56:23 [Server] INFO 2022-01-07 08:56:23,900 Server thread WARN org.apache.logging.log4j.io.LoggerPrintStream caught java.lang.ThreadDeath logging ReusableSimpleMessage: at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) java.lang.ThreadDeath
07.01 08:56:23 [Server] INFO at java.base/java.lang.Thread.stop(Thread.java:942)
07.01 08:56:23 [Server] INFO at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:1029)
07.01 08:56:23 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:839)
07.01 08:56:23 [Server] INFO at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1001)
07.01 08:56:23 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:29)
07.01 08:56:23 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
07.01 08:56:23 [Server] WARN at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478)
07.01 08:56:23 [Server] WARN at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:732)
07.01 08:56:23 [Server] WARN at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:508)
07.01 08:56:23 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:349)
07.01 08:56:23 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1218)
07.01 08:56:23 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
07.01 08:56:23 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
07.01 08:56:24 [Server] ERROR Main thread terminated by WatchDog due to hard crash
07.01 08:56:24 [Server] INFO java.lang.ThreadDeath: null
07.01 08:56:24 [Server] INFO at java.lang.Thread.stop(Thread.java:942) ~[?:?]
07.01 08:56:24 [Server] INFO at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1029) ~[purpur-1.18.1.jar:git-Purpur-1493]
07.01 08:56:24 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:839) ~[purpur-1.18.1.jar:git-Purpur-1493]
07.01 08:56:24 [Server] INFO at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:1001) ~[purpur-1.18.1.jar:git-Purpur-1493]
07.01 08:56:24 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.util.ServerShutdownThread.run(ServerShutdownThread.java:29) ~[purpur-1.18.1.jar:git-Purpur-1493]
07.01 08:56:24 [Server] INFO Stopping server
07.01 08:56:24 [Server] INFO Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
07.01 08:56:26 [Server] INFO Plugin disabled. Plugin created by xtomyserrax
07.01 08:56:26 [Server] INFO Stopping plugin!

**Comment by Wuemeli** [comment]
Thanks for Crashing my Server!

**Comment by MrMarL** [comment]
oh... I'm not sure it's up to me... and what do I need to do to get the same warning?
I only used standard save methods right?

**Comment by Wuemeli** [comment]
> oh... I'm not sure it's up to me... and what do I need to do to get the same warning? I only used standard save methods right?

Yes, When i start my Server with the newest Version of Oneblock the Server crashes

**Comment by MrMarL** [comment]
Does the problem still exist on the latest version of the plugin?
